### ISSUE TITLE
Question about data and request for network code

### ISSUE THREAD

**Issue by DachunKai** [intelpro/ELEDNet#2]
Hi, wonderful work!

I have two questions:

1. In the dataset, what is the relationship between the timestamp range of $E^t$ (event data) and the timestamp of $B^t$ (image exposure time)? Does $E^t$ represent the events occurring within the exposure time of $B^t$?

2. Could you kindly share the code for the proposed network?

**Comment by intelpro** [comment]
1) Yes, E^{t} represent the event voxels within the expsoure time. 

2) I will upload the code.

Thank you for the interest.

**Comment by intelpro** [comment]
We conducted the shooting without any dead time between exposures, meaning there was no gap between the exposure time and the subsequent exposure. Therefore, we can utilize these events directly.

**Comment by intelpro** [comment]
There is no events between B0 and B1. There is no delay time between blurred frame. Thanks.

**Comment by DachunKai** [comment]
Thank you! Are $B_0$ and $B_1$ blur images obtained by averaging multiple sharp frames?

**Comment by intelpro** [comment]
No. In the paper, I explained the dataset setup. I ask you to read the paper.
