### ISSUE TITLE
RELED dataset acquisition

### ISSUE THREAD

**Issue by ShuangMa156** [intelpro/ELEDNet#3]
Hello, thank you for your excellent work! I want to build a hybrid system consisting of event camera and RGB camera to get some data, but I don't know how to choose the model of beam splitter, can you help me？

**Comment by intelpro** [comment]
Hello, please e-mail me for more detailed question. I will close the issue.

**Comment by ShuangMa156** [comment]
Have you received my e-mail?&nbsp; Looking forward to hearing from you.
&nbsp;


马双
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Taewoo ***@***.***&gt;; 
发送时间: 2024年9月9日(星期一) 晚上7:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [intelpro/ELEDNet] RELED dataset acquisition (Issue #3)














 
Hello, please e-mail me for more detailed question. I will close the issue.
